# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnotozymi',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('crop', models.CharField(max_length=50)),
                ('s_ga', models.FloatField()),
                ('harvest', models.FloatField()),
                ('hatrv_inga', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
