# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalelim',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('gridcode', models.IntegerField()),
                ('area_ha', models.FloatField()),
                ('comment', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
