# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_map', '0003_auto_20160910_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldBorderl',
            new_name='WorldBorde',
        ),
    ]
